micronaut:
  application:
    name: micronautOtccPoc
  http:
    client:
      logger-name: externalGatewayLogger
    services:
      sessionManagerClient:
        logger-name: sessionMangerClientLogger
        url: ${app-config.session-manager-url}
      linkResolverClient:
        logger-name: linkResolverClientLogger
        url: ${app-config.linkresolver-base-url}
ehcache:
  storage-path: F:\Workshop\KAZ\java-projects\micronaut-otcc-poc\teststorage\caches
  caches:
    renderer:
      disk:
        max-size: 1Gb
logger:
  levels:
    example.poc: DEBUG
    example.poc.cache: DEBUG
    io.micronaut.cache: DEBUG
netty:
  default:
    allocator:
      max-order: 3
app-config:
  session-cookie-name: DEV_IBFD_SESSION
  publication-base-path: F:\Workshop\KAZ\java-projects\micronaut-otcc-poc\teststorage\publications
  test-url: https://dog.ceo
  session-manager-url: http://development7.ibfd.org:9000/sm.fpl
  limaserver-base-url: http://development7.ibfd.org:9080
  linkresolver-base-url: https://dev-research.ibfd.org/linkresolver/resolve
  linkresolver-use-post: true
  regional-pdf-xsl-url: jar:https://nexus3.ibfd.org/repository/ibfd-releases/org/ibfd/common-fop-pdf/1.0.54/common-fop-pdf-1.0.54.jar!/otcc-pdf-converter.xsl

