micronaut:
  application:
    name: OTCC
  http:
    client:
      logger-name: externalGatewayLogger
    services:
      sessionManagerClient:
        logger-name: sessionMangerClientLogger
        url: ${app-config.session-manager-url}
      linkResolverClient:
        logger-name: linkResolverClientLogger
        url: ${app-config.linkresolver-base-url}
ehcache:
  storage-path: D:\Workshop\poc\micronaut-otcc-poc\teststorage\caches
  caches:
    renderer:
      disk:
        max-size: 1Gb
logger:
  levels:
    org.ibfd.otcc': DEBUG
    org.ibfd.otcc.cache: INFO
    io.micronaut: INFO
netty:
  default:
    allocator:
      max-order: 3
app-config:
  session-cookie-name: DEV_IBFD_SESSION
  publication-base-path: D:\Workshop\poc\micronaut-otcc-poc\teststorage\publications
  session-manager-url: http://development7.ibfd.org:9000/sm.fpl
  limaserver-base-url: http://development7.ibfd.org:9080
  linkresolver-base-url: https://dev-research.ibfd.org/linkresolver/resolve

